### ISSUE TITLE
Make strong-debugger an optional dependency

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-supervisor#163] opened 2015-09-24 20:16 UTC
Because `strong-debugger` requires compiler tools (and Python), having it as a full dependency means that a compiler & Python are always required to install StrongLoop.  This is a new requirement; previously they were only required for DevOps features (profiling, metrics, etc).

Miroslav suggested:
> we could mark strong-debugger as an optional dependency of strong-supervisor, and then return a helpful error message when somebody attempts to start a debugger

 If it were an optional dependency, then installation requirements would revert to their previous status.

@ijroth @chandadharap @rmg

**Comment by chandadharap** [comment] 2015-09-24 20:26
Id like to make it optional for now, simply to avoid issues until we are
ready to include the feature in Arc.

We still need a long term solution. Are distros our only option?

- Chanda

On Thursday, September 24, 2015, Rand McKinney <notifications@github.com>
wrote:

> Because strong-debugger requires compiler tools (and Python), having it
> as a full dependency means that a compiler & Python are always required to
> install StrongLoop. This is a new requirement; previously they would only
> be required for DevOps features (profiling, metrics, etc).
>
> Miroslav suggested:
>
> we could mark strong-debugger as an optional dependency of
> strong-supervisor, and then return a helpful error message when somebody
> attempts to start a debugger
>
> If it were an optional dependency, then installation requirements would
> revert to their previous status.
>
> @ijroth <https://github.com/ijroth> @chandadharap
> <https://github.com/chandadharap> @rmg <https://github.com/rmg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/strong-supervisor/issues/163>.
>


-- 
Chanda Dharap
Director, Engineering
@StrongLoop Inc
(510) 304-3924
chanda@strongloop.com

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by bajtos** [comment] 2015-09-25 14:18
FWIW, this is a duplicate of https://github.com/strongloop-internal/scrum-loopback/issues/504. Let's keep both issues open, as the other on is in a private repo.

**Comment by rmg** [comment] 2015-10-14 22:19
#164 marked the dependency as optional, but it's not actually optional since supervisor crashes without it: strongloop/strong-pm#286.

**Comment by bajtos** [comment] 2015-10-15 06:40
> #164 marked the dependency as optional, but it's not actually optional since supervisor crashes without it: strongloop/strong-pm#286.

I believe https://github.com/strongloop/strong-supervisor/pull/166 should have fixed that problem.

**Closed** 2015-10-15 06:41 UTC
Labels: #tob, Needs Doc

**Comment by crandmck** [comment] 2015-10-15 17:22
I changed the docs back to say that compiler & Python are required only for DevOps features (profiling, metrics, etc).
